### ISSUE TITLE
Support for images without transparency

### ISSUE THREAD

**Issue by adnandossaji** [nanolaboratory/nft-toolkit#7]
We should allow for NFT collection that includes a background or in general, doesn't include any transparent pixels.

I get this when my NFT collection includes a background.

```
Traceback (most recent call last):
  File "/Users/adnan/Work/example-nft-toolkit/nft_generator.py", line 8, in <module>
    nft_collection.generate_collection()
  File "/Users/adnan/Work/example-nft-toolkit/venv/lib/python3.9/site-packages/nft/image.py", line 203, in generate_collection
    self.layer_attributes(images_paths)
  File "/Users/adnan/Work/example-nft-toolkit/venv/lib/python3.9/site-packages/nft/image.py", line 187, in layer_attributes
    nft_image.paste(attribute_image, (0, 0), mask=attribute_image)
  File "/Users/adnan/Work/example-nft-toolkit/venv/lib/python3.9/site-packages/PIL/Image.py", line 1582, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask
```

Can we support this?

**Comment by ndossaji** [comment]
Good catch! Fixed it with #8 PR.
